"""initial schema: claims, audit_events, training_feedback, users

Revision ID: 2d15d5af8d7c
Revises: 
Create Date: 2026-09-18 14:57:19.017588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d15d5af8d7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_trace_id'), 'audit_events', ['trace_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_claim_data', sa.JSON(), nullable=False),
    sa.Column('policy_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claims_policy_id'), 'claims', ['policy_id'], unique=False)
    op.create_table('training_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('fraud_verdict', sa.String(length=16), nullable=False),
    sa.Column('prediction_recommendation', sa.String(length=16), nullable=False),
    sa.Column('prediction_confidence', sa.Float(), nullable=False),
    sa.Column('adjuster_decision', sa.String(length=16), nullable=False),
    sa.Column('adjuster_reasoning', sa.Text(), nullable=False),
    sa.Column('adjuster_id', sa.String(length=128), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_feedback_claim_id'), 'training_feedback', ['claim_id'], unique=False)
    op.create_index(op.f('ix_training_feedback_trace_id'), 'training_feedback', ['trace_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('roles', sa.String(length=256), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_feedback_trace_id'), table_name='training_feedback')
    op.drop_index(op.f('ix_training_feedback_claim_id'), table_name='training_feedback')
    op.drop_table('training_feedback')
    op.drop_index(op.f('ix_claims_policy_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_audit_events_trace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
